services:
  carkit:
    image: ariiees/carkit:latest
    container_name: carkit
    privileged: true
    network_mode: host
    runtime: nvidia
    ipc: host
    shm_size: 6g
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /dev/shm:/dev/shm
      - ..:/workspaces/CARKit
    working_dir: /workspaces/CARKit
    command: bash
