joy:
  ros__parameters:
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval_ms: 50

joy_rate_filter:
  ros__parameters:
    input_topic: joy_device
    output_topic: joy
    publish_rate: 10.0

joy_teleop:
  ros__parameters:
    mode_toggle_button: 10
    manual_mode_initial: true
    manual_command_names: [human_control]
    autonomy_enable_topic: enable_autonomous_control

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 2.0
          offset: 0.0
        drive-steering_angle:
          axis: 2
          scale: 0.2
          offset: 0.0
