behavior_center_node:
  ros__parameters:
    min_confidence: 0.55
    detection_timeout_sec: 0.5
    scan_topic: /scan
    odom_topic: /odom
    scan_timeout_sec: 0.5
    camera_info_topic: /camera/camera/color/camera_info
    camera_horizontal_fov_deg: 69.4
    camera_to_scan_yaw_offset_rad: 0.0
    camera_forward_offset_m: 0.08
    camera_lateral_offset_m: 0.0
    global_plan_topic: /plan
    stop_sign_stop_before_distance_m: 1.0
    stop_sign_stop_line_tolerance_m: 0.25
    stop_sign_rearm_distance_m: 1.0
    stop_sign_lidar_angle_window_deg: 8.0
    stop_sign_lidar_min_range_m: 0.15
    stop_sign_lidar_max_range_m: 10.0
    stop_sign_stop_duration_sec: 5.0
    stop_sign_cooldown_sec: 10.0
    stop_sign_min_confidence: 0.6
    stop_sign_map_frame: map
    robot_base_frame: base_link
    stop_sign_required_observations: 2
    stop_sign_track_match_distance_m: 1.0
    stop_sign_clear_distance_m: 10.0
    traffic_light_min_confidence: 0.6
    traffic_light_lidar_angle_window_deg: 20.0
    traffic_light_lidar_min_range_m: 0.15
    traffic_light_lidar_max_range_m: 10.0
    traffic_light_stop_ahead_distance_m: 2.0
    traffic_light_required_observations: 2
    traffic_light_stop_required_frames: 2
    traffic_light_green_required_frames: 2
    traffic_light_track_match_distance_m: 1.0
    traffic_light_clear_distance_m: 10.0
    plan_goal_change_distance_m: 0.25
